### ISSUE TITLE
Dziwny bug na niektórych urządzeniach

### ISSUE THREAD

**Issue by mnojek** [Motoryka/FriendlyLines#46]
Na niektórych urządzeniach (np. tablet p. Landowskiej - model dopiszę później) podczas rysowania nagle pojawiają się dziwne linie, zawsze pod tym samym kątem (jakieś 45 stopni) od poziomu urządzenia, o grubości niezwiązanej z aktualną grubością linii.

**Comment by nojas10** [comment]
Naprawione
